### PR TITLE
Implement a new NSQ sink

### PR DESCRIPTION
**Pull request by jvrplmlmn**
This PR implements a new sink type: NSQ (http://nsq.io/).

Testing can be done using the `nsqio/nsq` Docker images: http://nsq.io/deployment/docker.html

### CODE REVIEW

**Comment by jvrplmlmn** [comment]
```
$ ./firehose
INFO[0000] Trying to acquire leader lock
INFO[0000] Lock acquired
INFO[0000] [sink/nsq] SINK_NSQ_ADDR=nsqd.service.consul:4150
INFO[0000] [sink/nsq] SINKSINK_NSQ_TOPIC_NAME_NSQ_ADDR=nomad-firehose
INFO[0000] No Last Change Time restore point, starting from scratch
INFO[0000] [sink/nsq/1] Starting writer
2017/10/28 16:31:57 INF    1 (nsqd.service.consul:4150) connecting to nsqd
INFO[0002] [sink/nsq/1] Publish OK
(...)
INFO[0002] [sink/nsq/1] Publish OK
INFO[0010] Writing lastChangedTime to KV: 1573883
^CINFO[0014] Caught signal, releasing lock and stopping...
INFO[0014] [sink/nsq] ensure write queue is empty (0 messages left)
INFO[0014] Writing lastChangedTime to KV: 1573883
$
```

screen shot 2017-10-28 at 18 34 36

**Comment by jvrplmlmn** [comment]
@jippi I'm not that familiar with `govendor`, more of a Glide dude, so could you let me know how I can update the vendored depencencies?

**Comment by jippi** [comment]
@jvrplmlmn looks you figured it out with govendor?  otherwise its just `govendor fetch $path` instead of `get get $path`

**Comment by jvrplmlmn** [comment]
Thanks for the help! I ran `govendor add github.com/nsqio/go-nsq/...` but that didn't fetch all the dependencies. I'll rebase with the branch with the latest changes in `master` and then push the correct vendored dependencies.

**Comment by jvrplmlmn** [comment]
@jippi CI has now a passing build (except because its stuck asking for the Dockerhub password 🤔 ).

**Comment by jippi** [comment]
@jvrplmlmn yeah, thats a bug i need to get fixed :)

**Comment by jippi** [comment]
Thanks!

**Comment by josegonzalez** [comment]
Probably should be mentioned in docs :)

**Pull request merged**
